../../target/mgr/mgr_load.o: mgr_load.c \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../platform/procdefs.h \
 ../ncx/log.h ../ncx/status.h mgr.h ../ncx/cap.h ../ncx/ncxtypes.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 ../ncx/dlq.h ../ncx/xmlns.h ../ncx/val.h ../ncx/ncxconst.h ../ncx/op.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/tk.h \
 ../ncx/xml_util.h /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../ncx/cfg.h ../ncx/ncx.h \
 ../ncx/grp.h ../ncx/obj.h ../ncx/rpc.h ../ncx/xml_msg.h ../ncx/yang.h \
 ../ncx/ext.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/ses.h ../ncx/val_util.h ../ncx/ncxmod.h \
 ../ncx/help.h mgr_load.h mgr_ses.h mgr_val_parse.h ../ncx/ses.h \
 ../ncx/status.h ../ncx/xml_util.h
