../../target/agt/agt_not.o: agt_not.c ../platform/procdefs.h agt.h \
 ../ncx/help.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../ncx/ncxconst.h ../ncx/obj.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 ../ncx/grp.h ../ncx/ncxtypes.h ../ncx/dlq.h ../ncx/xmlns.h \
 ../ncx/status.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../ncx/xml_msg.h ../ncx/log.h \
 agt_acm.h ../ncx/ses.h ../ncx/xpath.h ../ncx/var.h ../ncx/runstack.h \
 ../ncx/yang.h ../ncx/ext.h agt_cap.h ../ncx/cap.h agt_cb.h ../ncx/op.h \
 ../ncx/rpc.h ../ncx/status.h ../ncx/val.h agt_not.h agt_rpc.h \
 ../ncx/cfg.h ../ncx/ncx.h ../ncx/plock.h ../ncx/val_util.h \
 ../ncx/rpc_err.h agt_ses.h ../ncx/getcb.h agt_tree.h agt_util.h \
 agt_xpath.h ../ncx/ncxmod.h ../ncx/ncxtypes.h ../ncx/ses_msg.h \
 ../ncx/tstamp.h ../ncx/val_util.h ../ncx/xmlns.h ../ncx/xml_util.h \
 ../ncx/xml_wr.h ../ncx/yangconst.h
