../../target/agt/agt_val_parse.o: agt_val_parse.c \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../platform/procdefs.h agt.h \
 ../ncx/help.h ../ncx/ncxconst.h ../ncx/obj.h \
 /usr/include/libxml2/libxml/xmlregexp.h ../ncx/grp.h ../ncx/ncxtypes.h \
 ../ncx/dlq.h ../ncx/xmlns.h ../ncx/status.h ../ncx/tk.h ../ncx/rpc.h \
 ../ncx/op.h ../ncx/val.h ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h \
 ../ncx/xml_util.h ../ncx/xml_msg.h ../ncx/log.h agt_ses.h ../ncx/getcb.h \
 ../ncx/ses.h agt_top.h agt_util.h ../ncx/cfg.h ../ncx/ncx.h \
 ../ncx/yang.h ../ncx/ext.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/val_util.h agt_val_parse.h agt_xml.h \
 ../ncx/b64.h ../ncx/def_reg.h ../ncx/dlq.h ../ncx/ncx.h ../ncx/ncx_num.h \
 ../ncx/ncx_str.h ../ncx/ncx_list.h ../ncx/ncxconst.h ../ncx/ncxtypes.h \
 ../ncx/obj.h ../ncx/status.h ../ncx/tk.h ../ncx/typ.h ../ncx/val.h \
 ../ncx/val_util.h ../ncx/xmlns.h ../ncx/xml_util.h ../ncx/xpath.h \
 ../ncx/xpath_yang.h ../ncx/xpath1.h ../ncx/yangconst.h
