
#ifndef _H_test
#define _H_test
/* 

*** Generated by yangdump 0.9.8.519M
*** Copyright (c) 2009, Netconf Central, Inc., All Rights Reserved.

    module test
    revision 2009-11-20

    namespace http://netconfcentral.com/ns/test
    organization Netconf Central

 */

#include <xmlstring.h>

#ifndef _H_dlq
#include "dlq.h"
#endif

#ifndef _H_ncxtypes
#include "ncxtypes.h"
#endif

#ifndef _H_status
#include "status.h"
#endif

#define y_test_M_test (const xmlChar *)"test"
#define y_test_R_test (const xmlChar *)"2009-11-20"

#define y_test_I_tes_type (const xmlChar *)"tes-type"
#define y_test_I_white_bread (const xmlChar *)"white-bread"
#define y_test_I_wheat_bread (const xmlChar *)"wheat-bread"
#define y_test_I_wonder_bread (const xmlChar *)"wonder-bread"
#define y_test_I_frozen_waffle (const xmlChar *)"frozen-waffle"
#define y_test_I_frozen_bagel (const xmlChar *)"frozen-bagel"
#define y_test_I_hash_brown (const xmlChar *)"hash-brown"

#define y_test_N_cancel_tes (const xmlChar *)"cancel-tes"
#define y_test_N_make_tes (const xmlChar *)"make-tes"
#define y_test_N_tesDone (const xmlChar *)"tesDone"
#define y_test_N_tesStatus (const xmlChar *)"tesStatus"
#define y_test_N_test (const xmlChar *)"test"
#define y_test_N_testDoneness (const xmlChar *)"testDoneness"
#define y_test_N_testManufacturer (const xmlChar *)"testManufacturer"
#define y_test_N_testModelNumber (const xmlChar *)"testModelNumber"
#define y_test_N_testStatus (const xmlChar *)"testStatus"
#define y_test_N_testToastType (const xmlChar *)"testToastType"

/* container /test */
typedef struct y_test_T_test_ {
    xmlChar *testManufacturer;
    xmlChar *testModelNumber;
    xmlChar *testStatus;
} y_test_T_test;

/* container /make-tes/input */
typedef struct y_test_T_make_tes_input_ {
    uint32 testDoneness;
    val_idref_t *testToastType;
} y_test_T_make_tes_input;

/* notification /tesDone */
typedef struct y_test_T_tesDone_ {
    xmlChar *tesStatus;
} y_test_T_tesDone;

/* send a y_test_tesDone notification */
extern void
    y_test_tesDone_send (
    const xmlChar *tesStatus);

/* test module init 1 */
extern status_t
    y_test_init (
        const xmlChar *modname,
        const xmlChar *revision);

/* test module init 2 */
extern status_t
    y_test_init2 (void);

/* test module cleanup */
extern void
    y_test_cleanup (void);

#endif
