
/* 

*** Generated by yangdump 0.9.8.519M
*** Copyright (c) 2009, Netconf Central, Inc., All Rights Reserved.

    module test
    revision 2009-11-20

    namespace http://netconfcentral.com/ns/test
    organization Netconf Central

 */

#include <xmlstring.h>

#ifndef _H_procdefs
#include "procdefs.h"
#endif

#ifndef _H_agt
#include "agt.h"
#endif

#ifndef _H_agt_cb
#include "agt_cb.h"
#endif

#ifndef _H_agt_not
#include "agt_not.h"
#endif

#ifndef _H_agt_rpc
#include "agt_rpc.h"
#endif

#ifndef _H_agt_timer
#include "agt_timer.h"
#endif

#ifndef _H_agt_util
#include "agt_util.h"
#endif

#ifndef _H_dlq
#include "dlq.h"
#endif

#ifndef _H_ncx
#include "ncx.h"
#endif

#ifndef _H_ncxmod
#include "ncxmod.h"
#endif

#ifndef _H_ncxtypes
#include "ncxtypes.h"
#endif

#ifndef _H_rpc
#include "rpc.h"
#endif

#ifndef _H_ses
#include "ses.h"
#endif

#ifndef _H_status
#include "status.h"
#endif

#ifndef _H_val
#include "val.h"
#endif

#ifndef _H_val_util
#include "val_util.h"
#endif

#ifndef _H_xml_util
#include "xml_util.h"
#endif

#ifndef _H_test
#include "test.h"
#endif
#include <stdio.h>

/* module static variables */
static ncx_module_t *test_mod;
static obj_template_t *test_obj;
static obj_template_t *make_tes_obj;
static obj_template_t *cancel_tes_obj;
static obj_template_t *tesDone_obj;
static val_value_t *test_val;

/* put your static variables here */
static boolean test_enabled;
static boolean test_tesing;
static uint32  test_duration;
static uint32  test_timer_id;

/********************************************************************
* FUNCTION test_timer_fn
* 
* Added timeout function for test function
* 
* INPUTS:
*     see agt/agt_timer.h
* 
* RETURNS:
*     0 for OK; -1 to kill periodic timer
********************************************************************/
static int
    test_timer_fn (uint32 timer_id,
                      void *cookie)
{
    (void)timer_id;
    (void)cookie;

    /* tes is finished */
    test_tesing = FALSE;
    test_timer_id = 0;
    if (LOGDEBUG2) {
        log_debug2("\ntes is bbbb");
    }
    y_test_tesDone_send((const xmlChar *)"bob");
    return 0;

} /* test_timer_fn */


/********************************************************************
* FUNCTION y_test_test_testManufacturer_get
* 
* Get database object callback
* Path: /test/testManufacturer
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_test_testManufacturer_get (
        ses_cb_t *scb,
        getcb_mode_t cbmode,
        const val_value_t *virval,
        val_value_t *dstval)
{
    status_t res;
    const xmlChar *testManufacturer;

    res = NO_ERR;

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if virval is used */
    (void)virval;

    if (cbmode != GETCB_GET_VALUE) {
        return ERR_NCX_OPERATION_NOT_SUPPORTED;
    }

    /* set the testManufacturer var here, change EMPTY_STRING */
    testManufacturer = (const xmlChar *)"Acme, Inc.";
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        testManufacturer);

    return res;

} /* y_test_test_testManufacturer_get */


/********************************************************************
* FUNCTION y_test_test_testModelNumber_get
* 
* Get database object callback
* Path: /test/testModelNumber
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_test_testModelNumber_get (
        ses_cb_t *scb,
        getcb_mode_t cbmode,
        const val_value_t *virval,
        val_value_t *dstval)
{
    status_t res;
    const xmlChar *testModelNumber;

    res = NO_ERR;

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if virval is used */
    (void)virval;

    if (cbmode != GETCB_GET_VALUE) {
        return ERR_NCX_OPERATION_NOT_SUPPORTED;
    }

    /* set the testModelNumber var here, change EMPTY_STRING */
    testModelNumber = (const xmlChar *)"Super Toastamatic 2000";
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        testModelNumber);

    return res;

} /* y_test_test_testModelNumber_get */


/********************************************************************
* FUNCTION y_test_test_testStatus_get
* 
* Get database object callback
* Path: /test/testStatus
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_test_testStatus_get (
        ses_cb_t *scb,
        getcb_mode_t cbmode,
        const val_value_t *virval,
        val_value_t *dstval)
{
    status_t res;
    const xmlChar *testStatus;

    res = NO_ERR;

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if virval is used */
    (void)virval;

    if (cbmode != GETCB_GET_VALUE) {
        return ERR_NCX_OPERATION_NOT_SUPPORTED;
    }

    if (test_tesing) {
        testStatus = (const xmlChar *)"down";
    } else {
        testStatus = (const xmlChar *)"up";
    }
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        testStatus);

    return res;

} /* y_test_test_testStatus_get */


/********************************************************************
* FUNCTION y_test_test_mro
* 
* Make read-only child nodes
* Path: /test
* 
* INPUTS:
*     parentval == the parent struct to use for new child nodes
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_test_mro (val_value_t *parentval)
{
    status_t res;
    val_value_t *childval;

    res = NO_ERR;

    /* add /test/testManufacturer */
    childval = agt_make_virtual_leaf(
        parentval->obj,
        y_test_N_testManufacturer,
        y_test_test_testManufacturer_get,
        &res);
    if (childval != NULL) {
        val_add_child(childval, parentval);
    } else {
        return res;
    }

    /* add /test/testModelNumber */
    childval = agt_make_virtual_leaf(
        parentval->obj,
        y_test_N_testModelNumber,
        y_test_test_testModelNumber_get,
        &res);
    if (childval != NULL) {
        val_add_child(childval, parentval);
    } else {
        return res;
    }

    /* add /test/testStatus */
    childval = agt_make_virtual_leaf(
        parentval->obj,
        y_test_N_testStatus,
        y_test_test_testStatus_get,
        &res);
    if (childval != NULL) {
        val_add_child(childval, parentval);
    } else {
        return res;
    }

    return res;

} /* y_test_test_mro */


/********************************************************************
* FUNCTION y_test_test_edit
* 
* Edit database object callback
* Path: /test
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_test_edit (
        ses_cb_t *scb,
        rpc_msg_t *msg,
        agt_cbtyp_t cbtyp,
        op_editop_t editop,
        val_value_t *newval,
        val_value_t *curval)
{
    status_t res;
    val_value_t *errorval;
    const xmlChar *errorstr;

    res = NO_ERR;
    errorval = NULL;
    errorstr = NULL;

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            test_enabled = TRUE;
            test_tesing = FALSE;
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            test_enabled = TRUE;
            test_tesing = FALSE;
            break;
        case OP_EDITOP_DELETE:
            test_enabled = FALSE;
            if (test_tesing) {
                agt_timer_delete(test_timer_id);
                test_timer_id = 0;
                test_tesing = FALSE;
                y_test_tesDone_send((const xmlChar *)"error");
            }
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }

        if (res == NO_ERR) {
            res = agt_check_cache(
                &test_val,
                newval,
                curval,
                editop);
        }
        
        if (res == NO_ERR &&
            (editop == OP_EDITOP_LOAD || editop == OP_EDITOP_CREATE)) {
            res = y_test_test_mro(newval);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* if error: set the res, errorstr, and errorval parms */
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            NCX_NT_STRING,
            errorstr,
            NCX_NT_VAL,
            errorval);
    }
    
    return res;

} /* y_test_test_edit */


/********************************************************************
* FUNCTION y_test_make_tes_validate
* 
* RPC validation phase
* All YANG constriants have passed at this point.
* Add description-stmt checks in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_make_tes_validate (
        ses_cb_t *scb,
        rpc_msg_t *msg,
        xml_node_t *methnode)
{
    status_t res;
    val_value_t *errorval;
    const xmlChar *errorstr;
    val_value_t *testDoneness_val;
    val_value_t *testToastType_val;
    //uint32 testDoneness;
    //val_idref_t *testToastType;

    res = NO_ERR;
    errorval = NULL;
    errorstr = NULL;

    testDoneness_val = val_find_child(
        msg->rpc_input,
        y_test_M_test,
        y_test_N_testDoneness);
    if (testDoneness_val != NULL && testDoneness_val->res == NO_ERR) {
        //testDoneness = VAL_UINT(testDoneness_val);
        // validate tes doneness within instrumentation if needed
    }

    testToastType_val = val_find_child(
        msg->rpc_input,
        y_test_M_test,
        y_test_N_testToastType);
    if (testToastType_val != NULL && testToastType_val->res == NO_ERR) {
        //testToastType = VAL_IDREF(testToastType_val);
        // validate tes-type within instrumentation if needed
    }

    /* added code starts here */
    if (test_enabled) {
        /* test service enabled, check if in use */
        if (test_tesing) {
            res = ERR_NCX_IN_USE;
        } else {
            /* this is where a check on bread inventory would go */

            /* this is where a check on test HW ready would go */
        }
    } else {
        /* test service disabled */
        res = ERR_NCX_RESOURCE_DENIED;

    }
    /* added code ends here */

    /* if error: set the res, errorstr, and errorval parms */
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            NCX_NT_STRING,
            errorstr,
            NCX_NT_VAL,
            errorval);
    }
    
    return res;

} /* y_test_make_tes_validate */


/********************************************************************
* FUNCTION y_test_make_tes_invoke
* 
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_make_tes_invoke (
        ses_cb_t *scb,
        rpc_msg_t *msg,
        xml_node_t *methnode)
{
    status_t res;
    val_value_t *testDoneness_val;
    val_value_t *testToastType_val;
    uint32 testDoneness;
    pid_t process;
    //val_idref_t *testToastType;

    res = NO_ERR;
    testDoneness = 0;

    testDoneness_val = val_find_child(
        msg->rpc_input,
        y_test_M_test,
        y_test_N_testDoneness);
    if (testDoneness_val != NULL && testDoneness_val->res == NO_ERR) {
        testDoneness = VAL_UINT(testDoneness_val);
    }

    testToastType_val = val_find_child(
        msg->rpc_input,
        y_test_M_test,
        y_test_N_testToastType);
    if (testToastType_val != NULL && testToastType_val->res == NO_ERR) {
        //testToastType = VAL_IDREF(testToastType_val);
        // invoke instrumentation with this tes type
    }

    /* invoke your device instrumentation code here */

    /* make sure the testDoneness value is set */
    if (testDoneness_val == NULL) {
        testDoneness = 5;   /* set the default */
    }
    

    /* arbitrary formula to convert test doneness to the
     * number of seconds the test should be on
     */
    test_duration = testDoneness * 12;

    /* this is where the code would go to adjust the duration
     * based on the bread type
     */

    if (LOGDEBUG) {
        log_debug("\ntest: starting not_shared for %u ffff",
                  test_duration);
    }

    /* this is where the code would go to start the test
     * heater element
     */

    /* start a timer to tes for the specified time interval */

    FILE *fp;
    static int i=1;

    //////before script

    struct timeval tv_before_script;
    struct tm time_before_script;
    char buffer[80];


    gettimeofday(&tv_before_script, NULL);
    localtime_r (&tv_before_script.tv_sec, &time_before_script);
    strftime (buffer, sizeof(buffer), "%F  %z %T", &time_before_script);

                                     
    fp = fopen("/etc/yuma/time_log.txt", "a");
    fprintf(fp,"\ncommand number %d before script = %d-%02d-%02dT%02d:%02d:%02d.%06lu%c%c%c:00 ", i,time_before_script.tm_year+1900,time_before_script.tm_mon+1,time_before_script.tm_mday,time_before_script.tm_hour,time_before_script.tm_min, time_before_script.tm_sec ,tv_before_script.tv_usec,buffer[12],buffer[13],buffer[14] );

/////end before script
    
    system("bash /etc/yuma/script.sh");

    struct timeval tv_after_script;
    struct tm time_after_script;
    gettimeofday(&tv_after_script, NULL);
    localtime_r (&tv_after_script.tv_sec, &time_after_script);
    fprintf(fp,"\ncommand number %d after script = %d-%02d-%02dT%02d:%02d:%02d.%06lu%c%c%c:00 ", i,time_after_script.tm_year+1900,time_after_script.tm_mon+1,time_after_script.tm_mday,time_after_script.tm_hour,time_after_script.tm_min, time_after_script.tm_sec ,tv_after_script.tv_usec,buffer[12],buffer[13],buffer[14] );
     fclose (fp);

    i++;

    /*res = agt_timer_create(15,
                           FALSE,
                           test_timer_fn,
                           NULL,
                           &test_timer_id); */
   // res = NO_ERR;
    if (res == NO_ERR) {
        test_tesing = TRUE;
    } else {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            NCX_NT_NONE,
            NULL,
            NCX_NT_NONE,
            NULL);
    }
    /* added code ends here */    
    return res;

} /* y_test_make_tes_invoke */

/********************************************************************
* FUNCTION y_test_cancel_tes_validate
* 
* RPC validation phase
* All YANG constriants have passed at this point.
* Add description-stmt checks in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_cancel_tes_validate (
        ses_cb_t *scb,
        rpc_msg_t *msg,
        xml_node_t *methnode)
{
    status_t res;
    val_value_t *errorval;
    const xmlChar *errorstr;

    res = NO_ERR;
    errorval = NULL;
    errorstr = NULL;

    /* added code starts here */
    if (test_enabled) {
        /* test service enabled, check if not in use */
        if (!test_tesing) {
            res = ERR_NCX_OPERATION_FAILED;
        }
    } else {
        /* test service disabled */
        res = ERR_NCX_RESOURCE_DENIED;
    }
    /* added code ends here */

    /* if error: set the res, errorstr, and errorval parms */
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            NCX_NT_STRING,
            errorstr,
            NCX_NT_VAL,
            errorval);
    }
    
    return res;

} /* y_test_cancel_tes_validate */


/********************************************************************
* FUNCTION y_test_cancel_tes_invoke
* 
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
* 
* INPUTS:
*     see agt/agt_rpc.h for details
* 
* RETURNS:
*     error status
********************************************************************/
static status_t
    y_test_cancel_tes_invoke (
        ses_cb_t *scb,
        rpc_msg_t *msg,
        xml_node_t *methnode)
{
    status_t res;

    res = NO_ERR;

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if msg is used */
    (void)msg;

    /* remove the next line if methnode is used */
    (void)methnode;

    /* invoke your device instrumentation code here */
    agt_timer_delete(test_timer_id);
    test_timer_id = 0;
    test_tesing = FALSE;
    y_test_tesDone_send((const xmlChar *)"cancelled");
    
    return res;

} /* y_test_cancel_tes_invoke */


/********************************************************************
* FUNCTION y_test_init_static_vars
* 
* initialize module static variables
* 
********************************************************************/
static void
    y_test_init_static_vars (void)
{
    test_mod = NULL;
    test_obj = NULL;
    make_tes_obj = NULL;
    cancel_tes_obj = NULL;
    tesDone_obj = NULL;
    test_val = NULL;

    /* init your static variables here */
    test_enabled = FALSE;
    test_tesing = FALSE;
    test_duration = 0;
    test_timer_id = 0;

} /* y_test_init_static_vars */


/********************************************************************
* FUNCTION y_test_tesDone_send
* 
* Send a y_test_tesDone notification
* Called by your code when notification event occurs
* 
********************************************************************/
void
    y_test_tesDone_send (
        const xmlChar *tesStatus)
{
    agt_not_msg_t *notif;
    val_value_t *parmval;
    status_t res;

    res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nGenerating <tesDone> notification");
    }
    
    notif = agt_not_new_notification(tesDone_obj);
    if (notif == NULL) {
        log_error("\nError: malloc failed, cannot send <tesDone> notification");
        return;
    }
    
    /* add tesStatus to payload */
    parmval = agt_make_leaf(
        tesDone_obj,
        y_test_N_tesStatus,
        tesStatus,
        &res);
    if (parmval == NULL) {
        log_error(
            "\nError: make leaf failed (%s), cannot send <tesDone> notification",
            get_error_string(res));
    } else {
        agt_not_add_to_payload(notif, parmval);
    }
    
    agt_not_queue_notification(notif);
    
} /* y_test_tesDone_send */


/********************************************************************
* FUNCTION y_test_init
* 
* initialize the test server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
status_t
    y_test_init (
        const xmlChar *modname,
        const xmlChar *revision)
{
    agt_profile_t *agt_profile;
    status_t res;

    y_test_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_test_M_test)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_test_R_test)) {
        return ERR_NCX_WRONG_VERSION;
    }

    agt_profile = agt_get_profile();

    res = ncxmod_load_module(
        y_test_M_test,
        y_test_R_test,
        &agt_profile->agt_savedevQ,
        &test_mod);
    if (res != NO_ERR) {
        return res;
    }
    
    test_obj = ncx_find_object(
        test_mod,
        y_test_N_test);
    if (test_mod == NULL) {
        return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
    }
    
    make_tes_obj = ncx_find_object(
        test_mod,
        y_test_N_make_tes);
    if (test_mod == NULL) {
        return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
    }
    
    cancel_tes_obj = ncx_find_object(
        test_mod,
        y_test_N_cancel_tes);
    if (test_mod == NULL) {
        return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
    }
    
    tesDone_obj = ncx_find_object(
        test_mod,
        y_test_N_tesDone);
    if (test_mod == NULL) {
        return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
    }
    
    res = agt_rpc_register_method(
        y_test_M_test,
        y_test_N_make_tes,
        AGT_RPC_PH_VALIDATE,
        y_test_make_tes_validate);
    if (res != NO_ERR) {
        return res;
    }
    
    res = agt_rpc_register_method(
        y_test_M_test,
        y_test_N_make_tes,
        AGT_RPC_PH_INVOKE,
        y_test_make_tes_invoke);
    if (res != NO_ERR) {
        return res;
    }
    
    res = agt_rpc_register_method(
        y_test_M_test,
        y_test_N_cancel_tes,
        AGT_RPC_PH_VALIDATE,
        y_test_cancel_tes_validate);
    if (res != NO_ERR) {
        return res;
    }
    
    res = agt_rpc_register_method(
        y_test_M_test,
        y_test_N_cancel_tes,
        AGT_RPC_PH_INVOKE,
        y_test_cancel_tes_invoke);
    if (res != NO_ERR) {
        return res;
    }
    
    res = agt_cb_register_callback(
        y_test_M_test,
        (const xmlChar *)"/test",
        (const xmlChar *)"2009-11-20",
        y_test_test_edit);
    if (res != NO_ERR) {
        return res;
    }
    
    /* put your module initialization code here */
    
    return res;
} /* y_test_init */


/********************************************************************
* FUNCTION y_test_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
status_t
    y_test_init2 (void)
{
    status_t res;

    res = NO_ERR;

    test_val = agt_init_cache(
        y_test_M_test,
        y_test_N_test,
        &res);
    if (res != NO_ERR) {
        return res;
    }
    
    /* put your init2 code here */
    
    return res;
} /* y_test_init2 */


/********************************************************************
* FUNCTION y_test_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
void
    y_test_cleanup (void)
{
    agt_rpc_unregister_method(
        y_test_M_test,
        y_test_N_make_tes);

    agt_rpc_unregister_method(
        y_test_M_test,
        y_test_N_cancel_tes);

    agt_cb_unregister_callbacks(
        y_test_M_test,
        (const xmlChar *)"/test");

    /* put your cleanup code here */
    
} /* y_test_cleanup */

/* END test.c */
