../../target/ydump/h.o: h.c /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../platform/procdefs.h c.h \
 ../ncx/ses.h ../ncx/dlq.h ../ncx/ncxtypes.h \
 /usr/include/libxml2/libxml/xmlregexp.h ../ncx/xmlns.h ../ncx/status.h \
 ../ncx/tstamp.h ../ncx/yang.h ../ncx/ext.h ../ncx/ncxconst.h ../ncx/tk.h \
 ../ncx/grp.h ../ncx/obj.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/typ.h ../ncx/xml_util.h ../ncx/xml_msg.h \
 yangdump.h ../ncx/help.h c_util.h ../ncx/dlq.h ../ncx/ext.h h.h \
 ../ncx/ncx.h ../ncx/log.h ../ncx/ncxconst.h ../ncx/ncxmod.h ../ncx/cap.h \
 ../ncx/obj.h ../ncx/rpc.h ../ncx/status.h ../ncx/typ.h \
 ../ncx/yangconst.h yangdump_util.h
