../../target/ydump/html.o: html.c /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../platform/procdefs.h \
 ../ncx/dlq.h ../ncx/ext.h /usr/include/libxml2/libxml/xmlregexp.h \
 ../ncx/ncxconst.h ../ncx/ncxtypes.h ../ncx/xmlns.h ../ncx/status.h \
 ../ncx/tk.h ../ncx/grp.h html.h ../ncx/ses.h ../ncx/tstamp.h \
 ../ncx/yang.h ../ncx/obj.h ../ncx/grp.h ../ncx/rpc.h ../ncx/op.h \
 ../ncx/val.h ../ncx/dlq.h ../ncx/plock_cb.h ../ncx/typ.h \
 ../ncx/xml_util.h ../ncx/xml_msg.h yangdump.h ../ncx/help.h ../ncx/ncx.h \
 ../ncx/log.h ../ncx/ncxmod.h ../ncx/cap.h ../ncx/xml_val.h \
 ../ncx/xpath.h ../ncx/var.h ../ncx/runstack.h xsd_util.h \
 ../ncx/yangconst.h yangdump_util.h
