../../target/ydump/py_util.o: py_util.c \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../platform/procdefs.h c_util.h \
 ../ncx/ncxtypes.h /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 ../ncx/dlq.h ../ncx/xmlns.h ../ncx/status.h ../ncx/obj.h ../ncx/grp.h \
 ../ncx/ncxconst.h ../ncx/tk.h ../ncx/ncxtypes.h ../ncx/rpc.h ../ncx/op.h \
 ../ncx/val.h ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h \
 ../ncx/xml_util.h /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../ncx/xml_msg.h ../ncx/ses.h \
 yangdump.h ../ncx/help.h ../ncx/log.h ../ncx/ncx.h ../ncx/yang.h \
 ../ncx/ext.h ../ncx/ncx_str.h ../ncx/ncxmod.h ../ncx/cap.h py_util.h \
 ../ncx/yangconst.h yangdump_util.h
