../../target/ydump/ydump.o: ydump.c ../platform/procdefs.h c.h \
 ../ncx/ses.h /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../ncx/dlq.h ../ncx/ncxtypes.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h ../ncx/xmlns.h ../ncx/status.h \
 ../ncx/tstamp.h ../ncx/yang.h ../ncx/ext.h ../ncx/ncxconst.h ../ncx/tk.h \
 ../ncx/grp.h ../ncx/obj.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/typ.h ../ncx/xml_util.h ../ncx/xml_msg.h \
 yangdump.h ../ncx/help.h ../ncx/cli.h ../ncx/runstack.h ../ncx/conf.h \
 cyang.h h.h html.h ../ncx/log.h ../ncx/ncx.h ../ncx/ncx_feature.h \
 ../ncx/ncxconst.h ../ncx/ncxmod.h ../ncx/cap.h sql.h ../ncx/status.h \
 tg2.h ../ncx/val.h ../ncx/val_util.h ../ncx/plock.h ../ncx/xpath.h \
 ../ncx/var.h ../ncx/xmlns.h ../ncx/xml_util.h ../ncx/xml_wr.h \
 ../ncx/cfg.h xsd.h xsd_util.h ../ncx/yangconst.h yangdump_util.h \
 yangstats.h yangyin.h ydump.h
