../../target/ncx/xml_util.o: xml_util.c \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../platform/procdefs.h \
 def_reg.h ses.h dlq.h ncxtypes.h /usr/include/libxml2/libxml/xmlregexp.h \
 xmlns.h status.h tstamp.h log.h ncx.h grp.h ncxconst.h tk.h obj.h rpc.h \
 op.h val.h plock_cb.h typ.h xml_util.h xml_msg.h yang.h ext.h xpath.h \
 var.h runstack.h
