../../target/yangcli/yangcli.o: yangcli.c ../../../libtecla/libtecla.h \
 ../platform/procdefs.h ../ncx/cli.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../ncx/dlq.h ../ncx/ncxtypes.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 ../ncx/xmlns.h ../ncx/status.h ../ncx/obj.h ../ncx/grp.h \
 ../ncx/ncxconst.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../ncx/xml_msg.h \
 ../ncx/runstack.h ../ncx/conf.h ../ncx/help.h ../ncx/json_wr.h \
 ../ncx/ses.h ../ncx/val_util.h ../ncx/plock.h ../ncx/xpath.h \
 ../ncx/var.h ../ncx/yang.h ../ncx/ext.h ../ncx/log.h ../ncx/ncxmod.h \
 ../ncx/cap.h ../mgr/mgr.h ../ncx/cfg.h ../ncx/ncx.h ../mgr/mgr_hello.h \
 ../mgr/mgr_io.h ../mgr/mgr_not.h ../mgr/mgr_rpc.h ../mgr/mgr_ses.h \
 ../ncx/ncx.h ../ncx/ncx_list.h ../ncx/ncx_num.h ../ncx/ncx_str.h \
 ../ncx/ncxconst.h ../ncx/obj.h ../ncx/op.h ../ncx/rpc.h \
 ../ncx/runstack.h ../ncx/status.h ../ncx/val.h ../ncx/val_util.h \
 ../ncx/var.h ../ncx/xml_util.h ../ncx/xml_wr.h ../ncx/yangconst.h \
 yangcli.h yangcli_cmd.h ../ncx/rpc_err.h yangcli_alias.h \
 yangcli_autoload.h yangcli_autolock.h yangcli_save.h yangcli_tab.h \
 yangcli_uservars.h yangcli_util.h
