../../target/yangcli/yangcli_uservars.o: yangcli_uservars.c \
 ../platform/procdefs.h ../ncx/log.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../ncx/status.h \
 ../mgr/mgr_load.h ../ncx/obj.h /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 ../ncx/grp.h ../ncx/ncxconst.h ../ncx/ncxtypes.h ../ncx/dlq.h \
 ../ncx/xmlns.h ../ncx/tk.h ../ncx/rpc.h ../ncx/op.h ../ncx/val.h \
 ../ncx/plock_cb.h ../ncx/tstamp.h ../ncx/typ.h ../ncx/xml_util.h \
 /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h ../ncx/xml_msg.h ../ncx/ncx.h \
 ../ncx/yang.h ../ncx/ext.h ../ncx/status.h ../ncx/xml_util.h \
 ../ncx/xml_wr.h ../ncx/cfg.h ../ncx/plock.h ../ncx/xpath.h ../ncx/var.h \
 ../ncx/runstack.h ../ncx/ses.h ../ncx/val_util.h yangcli.h \
 ../../../libtecla/libtecla.h ../ncx/ncxmod.h ../ncx/cap.h ../ncx/help.h \
 ../mgr/mgr_io.h ../mgr/mgr_rpc.h yangcli_cmd.h ../ncx/rpc_err.h \
 yangcli_uservars.h yangcli_util.h
